#!/usr/bin/env zsh
set -e

SCRIPT_DIR=${0:a:h}
RESULT_DIR=${SCRIPT_DIR}/../commits/reproduction

# This script just wraps all commands of the README.md file

# 1.
cd ${SCRIPT_DIR}/crawl-redis
./crawl

cd ${SCRIPT_DIR}/analysis
./all ../crawl-redis/output/patches
cp commits.success ${RESULT_DIR}/redis.commits.success

# 2.
cd ${SCRIPT_DIR}/create-patched-patch-repository
./redis ${RESULT_DIR}/redis.commits.success

cd redis-server
git tag -l | grep wfpatch.patch- > ${RESULT_DIR}/redis.commits.success.wfpatch
cat ${RESULT_DIR}/redis.commits.success.wfpatch | sed 's/^wfpatch\.patch-//' > ${RESULT_DIR}/redis.commits.success.wfpatch.original

