#!/usr/bin/env zsh
set -e

if [ -z $1 ]; then
    echo "Please specify the directory of the MariaDB repository"
    exit 1
fi

SCRIPT_DIR=${0:a:h}

cd $1

git checkout -f mariadb-10.3.15
git reset --hard
git clean -xffd && git submodule foreach --recursive git clean -xffd
git submodule update --init
git am ${SCRIPT_DIR}/0001-Backport-Wait-Free-Codi-Patching-for-one-thread-per-.patch
git am ${SCRIPT_DIR}/0002-Add-original-wf-userland-library.patch
git am ${SCRIPT_DIR}/0003-Adjsut-syscalls-to-MMView-Kernel.patch
git am ${SCRIPT_DIR}/0004-Change-SIGNALHANDLER-to-FIFO.patch

git commit --allow-empty -m "Add empty commit because we always compile a pair and use the old version for execution."

set +e
git tag --delete mariadb-wf-10.3.15
set -e
git tag mariadb-wf-10.3.15

