#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}

cd ${SCRIPT_DIR}
if [ -d raw-data ]; then
	echo "raw-data already exists!"
	exit 0
fi

# Download
wget https://zenodo.org/records/11370684/files/raw-data.tar.xz
# Extract
tar xfJv raw-data.tar.xz
rm raw-data.tar.xz

