#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}

cd ${SCRIPT_DIR}
if [ -d transformed-data ]; then
	echo "transformed-data already exists!"
	exit 0
fi

# Download
wget https://zenodo.org/records/11370684/files/transformed-data.tar.xz
# Extract
tar xfJv transformed-data.tar.xz
rm transformed-data.tar.xz

