#!/usr/bin/env zsh

source ./INPUT_BASE_DIRECTORY
source OUTPUT_DIRECTORY
./exec-file-py --input-data $INPUT_BASE_DIRECTORY/one-thread-per-connection/one-thread-per-connection.duckdb --output $OUTPUT_DIRECTORY --plot arxiv-plot-latencies.R --prefix "OTPC-"
./exec-file-py --input-data $INPUT_BASE_DIRECTORY/threadpool/threadpool.duckdb --output $OUTPUT_DIRECTORY --plot arxiv-plot-latencies.R --prefix "TP-"

