#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}
cd ${SCRIPT_DIR}

if [ -d kpatch ]; then
    echo "kpatch directory already exists!"
    exit 0
fi

git clone https://github.com/dynup/kpatch.git
cd kpatch
git checkout 097bfa64555c95cea6774f96d00257c675a3f32e
git am ${SCRIPT_DIR}/0001-Commits-squashed-of-Rommel-et-al.patch
git am ${SCRIPT_DIR}/0002-Bump-to-v0.9.5.patch
make -j

