#!/usr/bin/env bash

set -ue

dir=$1
if [ ! -d ${dir} ]; then
    echo "${dir} is not a directory!"
    exit 1
fi


for benchmark_dir in `find ${dir} -type f -name log | xargs dirname | xargs dirname | uniq`; do
    benchmark_name=`basename ${benchmark_dir}`
    benchmark_name=${benchmark_name#"result-"} # remove "result-" prefix
    output_file=${benchmark_dir}/${benchmark_name}.duckdb

    if [ -f ${output_file} ]; then
        echo "Skipping '${output_file}'. File already exists!"
        continue
    fi
    
    if [[ "$BEDER_RANDOM_RUN_ID" == "1" ]]; then
        pipenv run python beder --benchmark ${benchmark_dir} --output ${output_file} --random-run-id > /dev/null &
    else
        pipenv run python beder --benchmark ${benchmark_dir} --output ${output_file} > /dev/null &
    fi
    echo "$! | ${output_file}"
done

FAIL=0
for job in `jobs -p`
do
    if wait $job; then
        echo "${job} Success"
    else
        let "FAIL+=1"
        echo "${job} Fail"
    fi
done

echo $FAIL
if [ "$FAIL" == "0" ]; then
    echo "Success!"
    exit 0
else
    echo "FAIL! ($FAIL)"
    exit 1
fi
