#!/usr/bin/env zsh

SCRIPT_DIR=${0:a:h}
cd ${SCRIPT_DIR}

blacklist=("redis-all-patches-load" "patch-one-by-one" "redis-1-200_400kB")

./transform-redis-all-patches

for dir in `ls -d ../data/*/`; do
    dir_name=`basename $dir`
    if (($blacklist[(Ie)$dir_name])); then
        # Element is contained in blacklist
        continue
    fi
    if [[ "$dir_name" == "threadpool-comparison" ]]; then
        export BEDER_RANDOM_RUN_ID=1
    else
        export BEDER_RANDOM_RUN_ID=0
    fi
    echo "#########################"
    echo "Transforming $dir"
    ./transform-experiment ${SCRIPT_DIR}/$dir
    echo "#########################"
    echo ""
done


