#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}

command -v pipenv >/dev/null 2>&1 || { echo >&2 "Could not find 'pipenv'. Please see the README in the 'qemu' directory on how to install python and pipenv (search for pyenv)."; exit 1; }

if python --version 2>&1 | grep -q '^Python 3\.10\.'; then
else
    echo >&2 "Could not find Python in version 3.10. Please see the README in the 'qemu' directory on how to install python (search for pyenv)."
    exit 1
fi

if ! git config --global --get user.name > /dev/null; then 
    echo "git config --global user.name must be set"
    exit 1
fi
if ! git config --global --get user.email > /dev/null; then 
    echo "git config --global user.email must be set"
    exit 1
fi

cd ${SCRIPT_DIR}/kpatch
./setup

cd ${SCRIPT_DIR}/mariadb-wfpatch-utils
./setup-cmake

cd ${SCRIPT_DIR}/benchbase
./setup

